// // utils/errorCodes.js
// module.exports = {
//   // Authentication & Authorization Errors
//   NO_TOKEN: "NO_TOKEN",
//   INVALID_USER_ID: "INVALID_USER_ID",
//   USER_NOT_FOUND: "USER_NOT_FOUND",
//   USER_INACTIVE: "USER_INACTIVE",
//   USER_LOCKED: "USER_LOCKED",
//   TOKEN_EXPIRED: "TOKEN_EXPIRED",
//   INVALID_TOKEN: "INVALID_TOKEN",
//   TOKEN_NOT_ACTIVE: "TOKEN_NOT_ACTIVE",
//   USER_NOT_AUTHENTICATED: "USER_NOT_AUTHENTICATED",
//   INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
//   RESOURCE_ACCESS_DENIED: "RESOURCE_ACCESS_DENIED",
//   AUTH_SERVER_ERROR: "AUTH_SERVER_ERROR",

//   // Generic API Errors
//   VALIDATION_ERROR: "VALIDATION_ERROR",
//   NOT_FOUND: "NOT_FOUND",
//   SERVER_ERROR: "SERVER_ERROR",
//   REQUEST_FAILED: "REQUEST_FAILED",

//   // Application-Specific Errors
//   DEVICE_ALREADY_ASSIGNED: "DEVICE_ALREADY_ASSIGNED",
//   TANK_ALREADY_ASSIGNED: "TANK_ALREADY_ASSIGNED",
//   UNSUPPORTED_DEVICE_TYPE: "UNSUPPORTED_DEVICE_TYPE",
//   INVALID_PERIOD: "INVALID_PERIOD",
// };



// utils/errorCodes.js
module.exports = {
  // Authentication & Authorization Errors
  NO_TOKEN: "NO_TOKEN",
  INVALID_USER_ID: "INVALID_USER_ID",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_INACTIVE: "USER_INACTIVE",
  USER_LOCKED: "USER_LOCKED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_NOT_ACTIVE: "TOKEN_NOT_ACTIVE",
  USER_NOT_AUTHENTICATED: "USER_NOT_AUTHENTICATED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  RESOURCE_ACCESS_DENIED: "RESOURCE_ACCESS_DENIED",
  AUTH_SERVER_ERROR: "AUTH_SERVER_ERROR",

  // Generic API Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  SERVER_ERROR: "SERVER_ERROR",
  REQUEST_FAILED: "REQUEST_FAILED",
  DEPRECATED_ENDPOINT: "DEPRECATED_ENDPOINT", // Added for sensorRoutes

  // Application-Specific Errors
  DEVICE_ALREADY_ASSIGNED: "DEVICE_ALREADY_ASSIGNED",
  TANK_ALREADY_ASSIGNED: "TANK_ALREADY_ASSIGNED",
  UNSUPPORTED_DEVICE_TYPE: "UNSUPPORTED_DEVICE_TYPE",
  INVALID_PERIOD: "INVALID_PERIOD",
};
